### ISSUE TITLE
Changing user image/group image doesn't work anymore

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#127]
Any call of these methods now throw the following error:

![image](https://user-images.githubusercontent.com/60986851/226063287-f2aa3ea8-b65a-42f8-a06f-afeb331a4cc4.png)
![image](https://user-images.githubusercontent.com/60986851/226063291-2f3004b9-7726-4942-a03a-1dab66e40eb3.png)

**Comment by julianzangl** [comment]
Average Layer 8 problem
