### ISSUE TITLE
cannot GET appointments synchronized via WebUntis

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#130]
Throws the following error
![image](https://user-images.githubusercontent.com/60986851/226710431-8fc6f72e-d0ac-4c96-af1d-df82e984f723.png)

**Comment by Nekonyx13** [comment]
![image](https://user-images.githubusercontent.com/60986851/226710631-e7431499-0073-446d-96f6-35ffb71ab9c8.png)

I guess das appointment hat keinen creator

**Comment by Lizardl** [comment]
creator gelöscht
