### ISSUE TITLE
Datenübergabe im Request Body

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#15]
> "Usually the content body is used for the data that is to be uploaded/downloaded to/from the server and the query parameters are used to specify the exact data requested." - Typ auf StackOverflow

Deshalb würde ich sagen lass defaultmäßig die Sachen im Body übergeben. Ausnahmen wären dann halt z.B. GETs für einzelne Tasks wo man dann die id als Parameter übergibt. Aber actually würd ich sowas dann eh mit Slugs machen (issue for this coming soon)

**Comment by julianzangl** [comment]
Ich hab jz noch nicht wirklich eine schöne Lösung gefunden wie man das handhaben kann, ich oder @Lizardl würden das dann mit Weiss besprechen, ob er eine Lösung kennt.

**Comment by Nekonyx13** [comment]
> Ich hab jz noch nicht wirklich eine schöne Lösung gefunden wie man das handhaben kann, ich oder @Lizardl würden das dann mit Weiss besprechen, ob er eine Lösung kennt.

dann lad ihn in die EveryTask Organsation ein und erwähn ihn hier, I dare you

**Comment by julianzangl** [comment]
done, see Postman doc
