### ISSUE TITLE
Endpoint Wiederverwendung mit GET, POST, DELETE, etc.

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#16]
Ich würds sexy finden wenn wir anstatt:

`api/task/get?pk_task_id=...`
`api/task/add`
`api/task/remove?pk_task_id=...`  

lieber sowas wie

`GET /api/tasks/[id]`
`POST /api/tasks`
`DELETE /api/tasks/[id]`

verwenden könnten damit die Endpoints übersichtlich bleiben und wir sie wiederverwenden können. Slugs sind da auch geil weil man nicht den query parameter benennen muss.

in der Discord API Documentation wird das ziemlich gut gezeigt. `task/edit` wäre in dem Fall dann auch ein `PATCH`
https://discord.com/developers/docs/resources/emoji#delete-guild-emoji

**Comment by julianzangl** [comment]
done, see postman doc
