### ISSUE TITLE
Set creation time server-side when a task gets added

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#19]
Ich weiß, wir können es am Client sortieren aber trotzdem wäre defaultmäßig `creation_time` besser weil mit id taucht mein Task irgendwo random auf wenn ich ihn hinzufüge. + wir müssen es nicht auf beiden Frontends auf die gleiche Weise sortieren

**Comment by Nekonyx13** [comment]
ist ja schön und gut aber ihr trägt die `create_time` nicht ein deshalb ist sie immer null also hat sich nichts geändert


![cat-fish-eye](https://user-images.githubusercontent.com/60986851/199245522-db5c073d-f790-4e2d-83f7-7c526a8be1e0.gif)

**Comment by julianzangl** [comment]
Wir sind davon ausgegangen, dass ihr uns das create_time mitgebt.
Create_time wird jetzt im Backend erstellt.

**Comment by Nekonyx13** [comment]
Achso ja, machen wir lieber nicht sonst kann es clientseitig modifiziert werden
