### ISSUE TITLE
Task is only assignable to one Group?

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#34]
Ihr habt noch keine Zwischentabelle zwischen Tasks und Groups, stattdessen kann momentan nur eine Gruppe pro Task festgelegt werden.

Aber wir wollen ja eigentlich mehrere Nutzer UND mehrere Gruppen einem Task zuweisen können.

Is this intended? Yes? No?

**Comment by julianzangl** [comment]
The foreign key of Group is in the task => it is possible to assign multiple tasks to one group

**Comment by Nekonyx13** [comment]
aber wir wollen ja einem task mehrere Gruppen zuweisen können? Heißt task und gruppen sind m zu n. Ein Task kann mehrere Gruppen haben und eine Gruppe kann mehrere Tasks haben

**Comment by julianzangl** [comment]
done
