### ISSUE TITLE
Can't update Task Date

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#44]
![image](https://user-images.githubusercontent.com/60986851/202860875-00b1d32f-696f-4c27-9e92-43401bef72a3.png)
![image](https://user-images.githubusercontent.com/60986851/202860876-5f04f48a-aaf1-4423-a5ea-cc43cea45004.png)

symfony gets confused with the date when receiving a task update

**Comment by Nekonyx13** [comment]
(adding a task works btw)

**Comment by julianzangl** [comment]
should be fixed
