### ISSUE TITLE
Please provide user object when changing username

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#52]
Please and thank you :)

**Comment by julianzangl** [comment]
done.

**Comment by Nekonyx13** [comment]
Cool anscheinend hat es @Lizardl  wieder zurückgeändert, danke. 
![image](https://user-images.githubusercontent.com/60986851/205461691-4bfdd40a-9743-44e9-a888-14dfef2fd420.png)

in dem commit
![image](https://user-images.githubusercontent.com/60986851/205461846-7aac6509-5b96-4eb1-b428-c023b8fdb315.png)

Ich weiß du meinst es gut aber bitte lass einfach die Finger von den Responses, vor allem in fucking main. Langsam wird es echt anstrengend,

**Comment by julianzangl** [comment]
fixed
