### ISSUE TITLE
Group members add up on GET groups call?

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#64]
Ich hab keine Ahnung wie euch sowas passiert aber bei GET groups werden die user aus den vorherigen gruppen zusammenaddiert
![image](https://user-images.githubusercontent.com/60986851/205518621-9248aa93-8c90-4ee9-959f-c2469c89013c.png)
in der 3ten gruppe hab ich dann schon 10 user im array drinnen

**Comment by Lizardl** [comment]
sorry... :(
