### ISSUE TITLE
Can't create a task with other users and no group

### ISSUE THREAD

**Issue by Nekonyx13** [HTL-EveryTask/everytask-backend#72]
![image](https://user-images.githubusercontent.com/60986851/207938468-b03f9cc0-7790-4543-b98a-b5b89de85308.png)

creating a task like this (with at least one explicit user and no groups) results in a success message, yet no task is added.

expected result: Task gets created with my own user and the given users as `assigned_users`

**Comment by julianzangl** [comment]
done
